#帮助列表
helplist:
  - title: 文本功能
    list:
      - title: "一言"
        desc: "随机一句话"
        icon: "71"
      - title: "古诗名句"
        desc: "发送一句古诗"
        icon: "147"
      - title: "名人一言"
        desc: "发送随机名人的一句话"
        icon: "139"
      - title: "网易云热评"
        desc: "发送网易云热评"
        icon: "145"
      - title: "人生哲理"
        desc: "发送一句人生哲理g"
        icon: "106"
      - title: "舔狗日记"
        desc: "舔狗不得hourse"
        icon: "101"
      - title: "土味情话"
        desc: "发送一句土味情话"
        icon: "135"
      - title: "骚话"
        desc: "发送一句骚话"
        icon: "230"
      - title: "口吐芬芳"
        desc: "注意文明"
        icon: "42"
      - title: "毒鸡汤"
        desc: "这汤有毒"
        icon: "47"
      - title: "笑话"
        desc: "这也笑不出来啊！"
        icon: "53"
      - title: "绕口令"
        desc: "绕来绕去"
        icon: "59"
      - title: "每日一文"
        desc: "来读一篇文章吧！"
        icon: "101"
      - title: "答案之书+问题"
        desc: "问一问，虽然没啥用"
        icon: "103"
      - title: "人间凑数"
        desc: "你也是来凑数的吗？"
        icon: "01"
      - title: "缘分张三和李四|缘分@1@2"
        desc: "看看你们之间的缘分"
        icon: "74"
      - title: "彩虹屁"
        desc: "吹吹彩虹屁"
        icon: "23"
      - title: "动漫/恋爱语录"
        desc: "发送随机动漫|恋爱|鼓励|孤独|搞笑|友情|歌词|伤感|经典|总裁|鲁迅|爱情公寓|社会）的一句话"
        icon: "58"
  - title: 图片功能
    list:
      - title: "米游社表情包1"
        desc: "0.原神，1.崩坏3，2.其他崩坏系列，3.其他，4.随机一种。为空则默认4"
        icon: "96"
      - title: "随机图片"
        desc: "随机一张二次元图片"
        icon: "88"
      - title: "原神壁纸"
        desc: "随机一张原神壁纸"
        icon: "71"
      - title: "随机cos"
        desc: "随机一张cos图片."
        icon: "74"
      - title: "随机acg"
        desc: "随机一张acg图片"
        icon: "174"
      - title: "甘城猫猫表情包"
        desc: "随机一张甘城猫猫表情包"
        icon: "181"
      - title: "原神黄历"
        desc: "今日份原神黄历"
        icon: "162"
      - title: "随机丝袜"
        desc: "随机一张丝袜图片"
        icon: "182"
      - title: "次元美图"
        desc: "随机一张二次元美图"
        icon: "176"
      - title: "摸鱼日历"
        desc: "今天继续摸鱼"
        icon: "162"
      - title: "男头"
        desc: "发送一张男头|女头|动漫头像|动漫男头|动漫女头图片"
        icon: "193"
      - title: 随机涩图
        desc: 返回一张一般涩的二次元图片
        icon: "60"
      - title: 水群统计
        desc: 返回一张水群统计图.
        icon: "141"
  - title: 管理员功能
    list:
      - title: "#千羽设置"
        desc: 显示所有设置
        icon: "100"
      - title: 千羽(强制)更新
        desc: 更新千羽插件
        icon: "86"
      - title: "#千羽关机/开机"
        desc: 关机忽略除开机外的所有指令（非关闭项目）
        icon: "95"
      - title: 只听主人的话|开私家车
        desc: 忽略除主人外的所有指令
        icon: "119"
      - title: 共享宠物|开公交车
        desc: 正常接受指令
        icon: "118"
      # - title: 涩图设置
      #   desc: 返回当前群的随机涩图设置
      #   icon: "29"
      # - title: 涩图设置(r18)+30
      #   desc: 涩图设置随机涩图/r18搜索cd
      #   icon: "58"
      # - title: 涩图设置(r18)撤回开启/关闭
      #   desc: 涩图设置随机涩图/r18搜索撤回开关
      #   icon: "59"
