#帮助列表
helplist:
  - title: "记录挖矿/狗粮时间" #指令
    desc: "记下当前时间挖矿时间，三/一天后提醒" #描述
  - title: "水晶矿/狗粮刷新时间"
    desc: "查看水晶矿狗粮冷却"
  - title: "挖矿记录"
    desc: "统计挖矿记录"
  - title: "水晶矿路线图"
    desc: "发送一张水晶矿采集路线图"
  - title: "定时列表"
    desc: "获取所有定时"
  - title: "测试刷新"
    desc: "获取所有定时"
