#帮助列表
helplist:
  - title: "记录挖矿/狗粮时间" #指令
    desc: "记下当前时间挖矿时间，三/一天后提醒" #描述
  - title: "水晶矿/狗粮刷新时间"
    desc: "查看水晶矿狗粮冷却"
  - title: "挖矿记录"
    desc: "统计挖矿记录"
  - title: "水晶矿路线图"
    desc: "发送一张水晶矿采集路线图"
  - title: "定时列表"
    desc: "获取所有定时"
  - title: "定时任务名称|内容|12:00@用户"
    desc: "自定义定时任务，可带一张图片，不@默认@自己"
  - title: "人间凑数"
    desc: "发送一句来自人间凑数的一段话"
  - title: "一言"
    desc: "随机一句话"
  - title: "古诗名句"
    desc: "发送一句古诗"
  - title: "每日一言"
    desc: "发送每日一言的图片"
  - title: "名人一言"
    desc: "发送随机名人的一句话"
  - title: "动漫/恋爱语录"
    desc: "发送随机（动漫、恋爱、鼓励、孤独、搞笑、友情、歌词、伤感、经典）的一句话"
  - title: "网易云热评"
    desc: "发送网易云热评"
  - title: "人生哲理"
    desc: "发送一句人生哲理"
  - title: "舔狗日记"
    desc: "舔狗不得hourse"
  - title: "土味情话"
    desc: "发送一句土味情话"
  - title: "骚话"
    desc: "发送一句骚话"
  - title: "口吐芬芳"
    desc: "注意文明"
