#帮助列表
helplist:
  - title: 文本功能
    list:
      - title: "一言"
        desc: "随机一句话"
      - title: "古诗名句"
        desc: "发送一句古诗"
      - title: "名人一言"
        desc: "发送随机名人的一句话"
      - title: "网易云热评"
        desc: "发送网易云热评"
      - title: "人生哲理"
        desc: "发送一句人生哲理"
      - title: "舔狗日记"
        desc: "舔狗不得hourse"
      - title: "土味情话"
        desc: "发送一句土味情话"
      - title: "骚话"
        desc: "发送一句骚话"
      - title: "口吐芬芳"
        desc: "注意文明"
      - title: "毒鸡汤"
        desc: "这汤有毒"
      - title: "笑话"
        desc: "这也笑不出来啊！"
      - title: "绕口令"
        desc: "绕来绕去"
      - title: "每日一文"
        desc: "来读一篇文章吧！"
      - title: "答案之书+问题"
        desc: "问一问，虽然没啥用"
      - title: "人间凑数"
        desc: "你也是来凑数的吗？"
      - title: "缘分张三和李四|缘分@1@2"
        desc: "看看你们直间的缘分"
      - title: "彩虹屁"
        desc: "吹吹彩虹屁"
      - title: "动漫/恋爱语录"
        desc: "发送随机（动漫、恋爱、鼓励、孤独、搞笑、友情、歌词、伤感、经典、总裁、鲁迅、爱情公寓、社会）的一句话"
  - title: 图片功能
    list:
      - title: "米游社表情包|米游社表情包1"
        desc: "0.原神，1.崩坏3，2.其他崩坏系列，3.其他，4.随机一种。为空则默认4"
      - title: "随机图片"
        desc: "随机一张二次元图片"
      - title: "原神壁纸"
        desc: "随机一张原神壁纸"
      - title: "随机cos"
        desc: "随机一张cos图片"
      - title: "随机acg"
        desc: "随机一张acg图片"
      - title: "甘城猫猫表情包"
        desc: "随机一张甘城猫猫表情包"
      - title: "原神黄历"
        desc: "今日份原神黄历"
      - title: "随机丝袜"
        desc: "随机一张丝袜图片"
      - title: "次元美图"
        desc: "随机一张二次元美图"
      - title: "摸鱼日历"
        desc: "今天继续摸鱼"
      - title: "抱枕"
        desc: "发送一张二次元抱枕图片"
      - title: "男头|女头|动漫头像|动漫男头|动漫女头"
        desc: "发送一张头像图片"
      - title: "随机涩图"
        desc: "不可以瑟瑟"
  - title: 管理员功能
    list:
      - title: 千羽设置
        desc: 显示所有设置
      - title: 千羽(强制)更新
        desc: 更新千羽插件
