imagelist:
  - name: 米游社表情包
    url: https://wenxin110.top/api/mys/memes?type=
    desc: 表情包类型：0.原神，1.崩坏3，2.其他崩坏系列，3.其他，4.随机一种。为空则默认4
    islist: false
  - name: 小姐姐图片
    url: http://fuyhi.top/api/tu_xjj/api.php
    desc: type//返回格式text/json可选image/jump
    islist: false
  - name: 小米壁纸
    url: http://fuyhi.top/api/xiaomi_bz/api.php #http://fuyhi.top/api/xiaomi_bz/api.php?form=风景&type=image
    desc: form//壁纸类型(精选，风景，星空，爱情，插画，科技，创意，汽车，美食，潮流)type//返回类型json/text/image/jump
    islist: false
  - name: 随机图片
    url: https://iw233.cn/API/Random.php
    desc: 国庆色图盲盒，概率出ssr
    islist: false
  -
